<a href="https://colab.research.google.com/github/MariiaSam/data_science/blob/main/1_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
! pip install numpy


In [3]:
import numpy as np

In [7]:
np.__version__



'1.26.4'

In [11]:
# Задаємо матрицю 3*3
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матриця:")
print(a)

Матриця:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
b = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матриця (ще один варіант):")
print(b)

Матриця (ще один варіант):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
a = np.array([[1, 2, 8, 4], [4, 75, 6, 4], [7, 8, 245, 4], [7, 575, 9, 4]])
print("Матриця:")
print(a)

b = np.array([[1, 2, -3, 4], [4, 65, 6, 4], [7, 8, 9, -4], [-7, 90, 9, 787]])
print("Матриця:")
print(b)

Матриця:
[[1 2 3 4]
 [4 5 6 4]
 [7 8 9 4]
 [7 8 9 4]]
Матриця:
[[ 1  2 -3  4]
 [ 4 65  6  4]
 [ 7  8  9 -4]
 [-7  8  9  4]]


In [20]:
print(a + b) # додаєм відповідні елементи
print(a - b)# віднімаємо відповідні елементи
print(a*b) # поелементне множення
print(a/b)

[[ 2  4  0  8]
 [ 8 70 12  8]
 [14 16 18  0]
 [ 0 16 18  8]]
[[  0   0   6   0]
 [  0 -60   0   0]
 [  0   0   0   8]
 [ 14   0   0   0]]
[[  1   4  -9  16]
 [ 16 325  36  16]
 [ 49  64  81 -16]
 [-49  64  81  16]]
[[ 1.          1.         -1.          1.        ]
 [ 1.          0.07692308  1.          1.        ]
 [ 1.          1.          1.         -1.        ]
 [-1.          1.          1.          1.        ]]


In [31]:
a = np.matrix([[1, 2], [4, 75]])
print("Матриця:")
print(a)

b = np.matrix([[3, 8], [4, 65]])
print("Матриця:")
print(b)

c = np.dot(a, b)
print(c)

d = np.dot(b, a)
print(d)

Матриця:
[[ 1  2]
 [ 4 75]]
Матриця:
[[ 3  8]
 [ 4 65]]
[[  11  138]
 [ 312 4907]]
[[  35  606]
 [ 264 4883]]


In [32]:
a = np.matrix([[1, 2], [4, 75], [3, 6]])
print("Матриця:")
print(a)

b = np.matrix([[3, 8], [4, 65]])
print("Матриця:")
print(b)

c = np.dot(a, b)
print(c)

Матриця:
[[ 1  2]
 [ 4 75]
 [ 3  6]]
Матриця:
[[ 3  8]
 [ 4 65]]
[[  11  138]
 [ 312 4907]
 [  33  414]]


In [35]:
# Визначник матриці
a = np.matrix([[1, 298], [3, 4.9]])
a_det = np.linalg.det(a)

print("Визначник матриці:")
print(a_det.round(2))

Визначник матриці:
-889.1


In [36]:
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [41]:
matrix = np.random.randint(2, size=(4, 4))
print(matrix)

[[0 1 0 0]
 [0 1 0 1]
 [1 1 1 0]
 [1 1 0 1]]


In [42]:
#матриця з одиниць
matrix = np.ones((3, 3), dtype=int)
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [45]:
# Побудуємо діагональ
diag = np.diag(matrix)
print("Діагональ:")
print(diag)



Діагональ:
[1 1 1]


In [46]:
# Побудуємо діагональну матрицю на основі діагоналі
m_diag_np = np.diag(np.diag(matrix))
print("Діагональна матриця:")
print(m_diag_np)


Діагональна матриця:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [49]:
 #Транспонована матриця
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Матриця a:")
print(a)
a_t = a.transpose()
print("Транспонована матриця:")
print(a_t)
print("Ще один спосіб транспонування матриці:")
print(a.T)

Матриця a:
[[1 2 3]
 [4 5 6]]
Транспонована матриця:
[[1 4]
 [2 5]
 [3 6]]
Ще один спосіб транспонування матриці:
[[1 4]
 [2 5]
 [3 6]]


In [50]:
a = np.matrix([[1, 3], [2, 5]])
a_det = np.linalg.det(a)
print("Визначник матриці:")
print(a_det.round(2))


Визначник матриці:
-1.0


In [54]:
a = np.matrix([[3, 4, 7], [5, 4, 2], [1, 0, 2]])
b = np.matrix([[3], [4], [7]])

In [56]:
x = np.linalg.solve(a, b)
print('Перевірка: ')
print('x =', x.round(1) )

Перевірка: 
x = [[ 25.2]
 [-35.2]
 [  9.9]]


In [61]:
a_inv = np.linalg.inv(a)
c = np.dot(a_inv, b)
print("перевірка: ")
print('x =', c.round(1))


перевірка: 
x = [[ 25.2]
 [-35.2]
 [  9.9]]
