<a href="https://colab.research.google.com/github/MariiaSam/data_science/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [125]:
import numpy as np


In [57]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

matrix = np.matrix([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(matrix)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [58]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matrix = np.zeros((3, 3), dtype=int)
print(matrix)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [96]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення

matrix = np.random.randint(1, 11, size=(5,5))

print(matrix)

[[ 7  7  3  8  6]
 [ 8  1  9 10  3]
 [10  8 10  7  2]
 [ 4 10  3  5  4]
 [ 9  3  1  3  5]]


In [97]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення
matrix = np.random.randint(2, size=(4,4))
print(matrix)

[[0 1 0 0]
 [1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]]


In [98]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення
a = np.random.randint(1, 11, size=(5), dtype=int)
b = np.random.randint(1, 11, size=(5), dtype=int)

print(a+b)

[14  7  6 15 16]


In [99]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([2, 4, 6, 1, 3, 5, 9])

print(np.dot(vector1, vector2))

140


In [100]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою
matrix1 = np.random.randint(1, 11, size=(2,2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2,3), dtype=int)

print(np.dot(matrix1, matrix2))

[[54 68 62]
 [ 9 11 11]]


In [101]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 11, size=(3,3), dtype=int)
matrix_inv = np.linalg.inv(matrix)
print(matrix_inv)


[[ 0.23595506 -0.19101124  0.03370787]
 [-0.73033708  1.06741573 -0.24719101]
 [ 0.1011236  -0.2247191   0.15730337]]


In [102]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її
matrix = np.random.rand(4, 4)
print(matrix.T)

[[2.11968264e-01 6.94728199e-01 8.15129307e-01 3.10238894e-01]
 [3.19161738e-01 2.72297914e-01 6.83092244e-01 6.82573698e-01]
 [5.46787957e-01 4.99807976e-01 5.79183851e-04 1.21743007e-01]
 [2.91240187e-01 2.71385885e-01 1.93363514e-01 9.72108284e-01]]


In [103]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор
matrix = np.random.randint(1, 11, size=(3,4), dtype=int)
vector = np.random.randint(1, 11, size=(4), dtype=int)
print(matrix*vector)

[[ 40  54   3 100]
 [  5  42   6 100]
 [ 10  12  21  50]]


In [104]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print(matrix*vector)

[[0.18038557 0.26506241 0.06717794]
 [0.3381364  0.04275292 0.26094685]]


In [105]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення
matrix1 = np.random.randint(1, 11, size=(2,2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2,2), dtype=int)

print(matrix1*matrix2)

[[ 3 21]
 [24 18]]


In [106]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток
matrix1 = np.random.randint(1, 11, size=(2,2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2,2), dtype=int)

print(np.dot(matrix1, matrix2))


[[ 16  99]
 [ 24 117]]


In [110]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці
matrix = np.random.randint(1, 101, size=(5,5), dtype=int)
print(matrix)

print(matrix.sum())

[[ 22  58  87  67  27]
 [ 78  92  15  28  94]
 [ 58  45  94  99  79]
 [ 29  86  91  70  89]
 [ 11  90  38 100  77]]
1624


In [113]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю
matrix1 = np.random.randint(1, 11, size=(4,4), dtype=int)
matrix2 = np.random.randint(1, 11, size=(4,4), dtype=int)

print(matrix1)
print(matrix2)

print(matrix1 - matrix2)

[[ 5  3 10  3]
 [ 8  2  9  1]
 [ 6  2  5  9]
 [ 2  9 10  9]]
[[ 2  8  5  7]
 [ 3 10  5  7]
 [ 4  8  5  2]
 [10  2  4  1]]
[[ 3 -5  5 -4]
 [ 5 -8  4 -6]
 [ 2 -6  0  7]
 [-8  7  6  8]]


In [118]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix = np.random.rand(3, 3)
print(matrix)
print(matrix.shape)

[[0.24118609 0.53297844 0.7871055 ]
 [0.23839089 0.84297698 0.24155457]
 [0.83628328 0.56176787 0.04157504]]
(3, 3)


In [124]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix = np.random.randint(0, 11, (3, 4))
print(matrix)

matrix2 = matrix * matrix
print(matrix2)

[[10 10  2  4]
 [ 4  7  7  0]
 [10  9  0  0]]
[[100 100   4  16]
 [ 16  49  49   0]
 [100  81   0   0]]


In [ ]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
