<a href="https://colab.research.google.com/github/MariiaSam/data_science/blob/main/lesson_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


In [ ]:
v1 = np.matrix([1, 2, 3, 4, 5])
print(v1)
v2 = v1.T
print(v2)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


1. Напишіть функцію, яка перевертає вектор у зворотному порядку

In [ ]:
v = np.array([1, 2, 3, 4, 5])
print(v[::-1])
v = np.flip(v)
print(v)

[5 4 3 2 1]
[5 4 3 2 1]


2.Обчислити середнє значення вектора

In [ ]:
print(np.mean(v))

3.0


3.Знайти найбільший і найменший елементи вектора

In [ ]:
print(np.max(v))
print(np.min(v))

5
1


4.Обчислити скалярний добуток (dot product) двох векторів

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(np.dot(v1, v2))
print(v1*v2)

32
[ 4 10 18]


5.Напишіть функцію, яка нормалізує вектор (зводить до одиничної довжини).

In [ ]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)
print(norm)
print(v/norm)

7.416198487095663
[0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]


6.Перевірити, чи є вектори ортогональними

In [ ]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
print(np.dot(v1, v2))

0


7. Визначити унікальні елементи вектора

In [ ]:
v = np.array([1, 2, 3, 2, 4, 5, 3])
print(np.unique(v))


[1 2 3 4 5]


8.Знайти вектор, що є різницею між двома векторами

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


9.Перевірити, до дорівнює довжина вектора 5

In [ ]:
vector = np.array([1,2,3, 4, 5])
length = np.linalg.norm(vector)
print(np.isclose(length, 5))

False


10. Задати матрицю, заповнену випадковими числами

In [ ]:
a = np.random.randint(0, 11, (3, 3))
print(a)

[[10  6  3]
 [ 8  0  0]
 [ 7  7  9]]


11. Обчислити визначник матриці

In [ ]:
print(np.linalg.det(a))

-264.00000000000017


12. Знаходження оберненої матриці

In [ ]:
print(np.linalg.inv(a))

[[ 0.00000000e+00  1.25000000e-01  1.11022302e-17]
 [ 2.72727273e-01 -2.61363636e-01 -9.09090909e-02]
 [-2.12121212e-01  1.06060606e-01  1.81818182e-01]]


13. Розв'яжіть систему лінійних рівнянь A⋅x=b, де A – матриця коефіцієнтів, 𝑏
 – вектор вільних членів.

In [ ]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])
x = np.linalg.solve(a, b)
print(x)
inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


14. Множення двох матриць

In [ ]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])
print(np.dot(a, b))

[-2 -6 16]


In [ ]:
a = np.matrix([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.matrix([5, 3, 4])
print(np.dot(a, b))

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [ ]:
a = np.matrix([[1, 3, -4], [0, 2, -3]])
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(a)
print(b)
print(np.dot(a, b))

[[ 1  3 -4]
 [ 0  2 -3]]
[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[-1  4  7]
 [-5  0  1]]


15. Транспонування матриці

In [ ]:
print(a.T)
print(b.T)

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


In [ ]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


16. Перевірка симетричності матриці

In [ ]:
matrix = np.matrix([[2, 2, 2],[2, 2, 2], [2,2,2]])
print(np.allclose(matrix, matrix.T))

True


17. Обчислення сліду матриці

In [ ]:
print(np.trace(matrix))

6


18. Сума матриць

In [ ]:
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


19. Піднесення матриці до ступеня

In [ ]:
a = np.matrix([[1, 2], [3, 4]])
print(np.linalg.matrix_power(a, 2))

[[ 7 10]
 [15 22]]


20.Сортування рядків або стовпців матриці

In [ ]:
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [ ]:
a = np.array([[1,4],[3,1]])
print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


In [ ]:
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))


[[1 1]
 [3 4]]
[[1 4]
 [1 3]]


In [ ]:
# Підрахунок суми елементів кожного рядка і зміна форми на (n, 1)
row_sums = np.sum(a, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)
#В результаті отримали вектор - стовпчик

Сума елементів кожного рядка:
[[5]
 [4]]
