In [31]:
# Додавання/віднімання скаляра та вектора

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a + 2)  # [3. 4. 5. 6. 7.]
print(a - 1)  # [0. 1. 2. 3. 4.]


[3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4.]


In [32]:
# Множення на скаляр

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)  # [1. 2. 3. 4. 5.]




[1. 2. 3. 4. 5.]


In [33]:
b = 5*a

print(b)  # [ 5. 10. 15. 20. 25.]

[ 5. 10. 15. 20. 25.]


In [34]:
# Додавання та віднімання двох векторів

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.size)  # 5


5


In [35]:
# А коли ми додамо, чи віднімемо між собою два вектори, то у нас попарно віднімуться чи просумуються відповідні елементи наших векторів:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]


[5 7 9]
[-3 -3 -3]


In [36]:
# Скалярний добуток
# Скалярним добутком двох векторів буде сума попарно перемножених відповідних координат цих двох векторів. 
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)  # [ 4 10 18]
# У даному випадку ми отримали не той результат, на який розраховували, оскільки ми виконали поелементне множення відповідних елементів і отримали новий вектор, а не скалярний добуток.

[ 4 10 18]


In [37]:
# щоб виконати скалярний добуток ми повинні виконати наступний скрипт:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))  # 32


32


In [38]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(b / a)  # [4.  2.5 2. ]


[4.  2.5 2. ]


In [39]:
# Оскільки ndarray є масивом, то створивши масив масивів, ми отримаємо матрицю:

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print(m)



[[1 2 3]
 [4 5 6]]


In [40]:
# Розмірність матриці, як і векторів, можна подивитись за допомогою даного атрибуту shape

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.shape)  # (5,)

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print(m.shape)  # (2, 3)


(5,)
(2, 3)


# Операції з матрицями будуть відбуватися таким самим чином, як і з вектором, оскільки це у нас масив масивів, окрім множення. Якщо ми будемо використовувати оператор ∗, то отримаємо поелементне множення всіх відповідних елементів двох матриць і можливо провести таку операцію лише для двох матриць однієї розмірності. Розглянемо це на прикладі:

In [41]:
a = np.array([[2, 3, 4, 5],
              [1, 2, 3, 4]])

b = np.array([[2, 2, 2, 2],
              [1, 1, 1, 1]])

print(a*b)


[[ 4  6  8 10]
 [ 1  2  3  4]]


# Множення матриць


In [42]:
import numpy as np

a = np.array([[1, 2, 3],
              [0, 1, 2]])

b = np.array([[ 1, 2],
              [ 0, 4],
              [-1, 0]])

c = np.dot(a, b)
print(c)


[[-2 10]
 [-2  4]]
