In [7]:
# Додавання/віднімання скаляра та вектора

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a + 2)  # [3. 4. 5. 6. 7.]
print(a - 1)  # [0. 1. 2. 3. 4.]


[3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4.]


In [8]:
# Множення на скаляр

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)  # [1. 2. 3. 4. 5.]




[1. 2. 3. 4. 5.]


In [19]:
b = 5*a

print(b)  # [ 5. 10. 15. 20. 25.]

[ 5 10 15]


In [20]:
# Додавання та віднімання двох векторів

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.size)  # 5


5


In [ ]:
# А коли ми додамо, чи віднімемо між собою два вектори, то у нас попарно віднімуться чи просумуються відповідні елементи наших векторів:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]


In [ ]:
# Скалярний добуток
# Скалярним добутком двох векторів буде сума попарно перемножених відповідних координат цих двох векторів. 
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)  # [ 4 10 18]
# У даному випадку ми отримали не той результат, на який розраховували, оскільки ми виконали поелементне множення відповідних елементів і отримали новий вектор, а не скалярний добуток.

In [ ]:
# щоб виконати скалярний добуток ми повинні виконати наступний скрипт:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))  # 32


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(b / a)  # [4.  2.5 2. ]
