In [31]:
# Додавання/віднімання скаляра та вектора

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a + 2)  # [3. 4. 5. 6. 7.]
print(a - 1)  # [0. 1. 2. 3. 4.]


[3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4.]


In [32]:
# Множення на скаляр

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)  # [1. 2. 3. 4. 5.]




[1. 2. 3. 4. 5.]


In [33]:
b = 5*a

print(b)  # [ 5. 10. 15. 20. 25.]

[ 5. 10. 15. 20. 25.]


In [34]:
# Додавання та віднімання двох векторів

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.size)  # 5


5


In [35]:
# А коли ми додамо, чи віднімемо між собою два вектори, то у нас попарно віднімуться чи просумуються відповідні елементи наших векторів:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]


[5 7 9]
[-3 -3 -3]


In [36]:
# Скалярний добуток
# Скалярним добутком двох векторів буде сума попарно перемножених відповідних координат цих двох векторів. 
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)  # [ 4 10 18]
# У даному випадку ми отримали не той результат, на який розраховували, оскільки ми виконали поелементне множення відповідних елементів і отримали новий вектор, а не скалярний добуток.

[ 4 10 18]


In [37]:
# щоб виконати скалярний добуток ми повинні виконати наступний скрипт:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))  # 32


32


In [38]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(b / a)  # [4.  2.5 2. ]


[4.  2.5 2. ]


In [39]:
# Оскільки ndarray є масивом, то створивши масив масивів, ми отримаємо матрицю:

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print(m)



[[1 2 3]
 [4 5 6]]


In [40]:
# Розмірність матриці, як і векторів, можна подивитись за допомогою даного атрибуту shape

import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.shape)  # (5,)

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print(m.shape)  # (2, 3)


(5,)
(2, 3)


# Операції з матрицями будуть відбуватися таким самим чином, як і з вектором, оскільки це у нас масив масивів, окрім множення. Якщо ми будемо використовувати оператор ∗, то отримаємо поелементне множення всіх відповідних елементів двох матриць і можливо провести таку операцію лише для двох матриць однієї розмірності. Розглянемо це на прикладі:

In [41]:
a = np.array([[2, 3, 4, 5],
              [1, 2, 3, 4]])

b = np.array([[2, 2, 2, 2],
              [1, 1, 1, 1]])

print(a*b)


[[ 4  6  8 10]
 [ 1  2  3  4]]


# Множення матриць


In [44]:
import numpy as np

a = np.array([[1, 2, 3],
              [5, 6, 7]])

b = np.array([[ 8, 9],
              [ 10, 11],
              [12, 13]])

c = np.dot(a, b)
print(c)


[[ 64  70]
 [184 202]]


# Транспонування та зміна форми матриць в numpy

# процес транспонування матриці — це заміна рядків матриці на її стовпці, а стовпців, відповідно, на рядки. Отримана в результаті матриця називається транспонованою. Символ операції транспонування — літера T


In [45]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)
b = a.T
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Розмірність вектора або матриці можна також змінювати методом reshape

In [47]:
import numpy as np

a = np.array([[1, 2, 3],
         [4, 5, 6]])

b = a.reshape((3, 2))
print(b)


[[1 2]
 [3 4]
 [5 6]]


# Також є можливість перетворення матриці в плоский вектор за допомогою методу flatten

In [48]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()
print(b)


[1 2 3 4 5 6]


# Одинична матриця
Одинична матриця — це квадратна матриця, у якої на головній діагоналі стоять одиниці, а всі інші елементи дорівнюють нулю

In [55]:
import numpy as np

a = np.eye(5, k=3, dtype=float)
print(a)


[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [56]:
import numpy as np

a = np.eye(5, k=1, dtype=float)
print(a)


[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [57]:
import numpy as np

a = np.eye(5, k=0, dtype=float)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Обернена матриця

In [58]:
import numpy as np

a = np.array([[ 1, 0, 3],
              [-1,-1, 2],
              [ 4, 7, 2]])

a_inv = np.linalg.inv(a)
print(a_inv)


[[ 0.64 -0.84 -0.12]
 [-0.4   0.4   0.2 ]
 [ 0.12  0.28  0.04]]


Інші можливості в NumPy

shape - вимірювання масиву, розмір масиву вздовж кожної з осей, повертається як кортеж цілих чисел

ndim - кількість осей (вимірювань)

size - Загальна к-сть елементів у масиві, рівна добутку елеменнтів кортежу shape

dtype - тип даних

data - буфер в памʼяті, що містить дійсніелементи масиву

itemsize - розмір байту кожного елемента

Щоб створити вектор або матрицю, які складаються з одиниць, використовують метод ones

In [59]:
import numpy as np

a = np.ones((5,), dtype=float)
print(a)

m = np.ones((2, 3), dtype=int)
print(m)


[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


Щоб створити вектор або матрицю, які складаються з нулів, використовують метод zeros

In [60]:
import numpy as np

a = np.zeros(5, dtype=float)
print(a)

m = np.zeros((2, 3), dtype=int)
print(m)


[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [ ]:
# Для створення масиву, що містить послідовність чисел, існують два методи: np.arange та np.linspace

In [61]:
import numpy as np

a = np.arange(5)
b = np.arange(1, 3, 0.5)
print(a)
print(b)


[0 1 2 3 4]
[1.  1.5 2.  2.5]


In [ ]:
# Щоб включити останній елемент визначеної послідовності, можна використовувати метод np.linspace

In [63]:
import numpy as np

a = np.linspace(1, 5, num=5)
b = np.linspace(1, 3, num=3)
print(a)
print(b)


[1. 2. 3. 4. 5.]
[1. 2. 3.]


In [ ]:
# Щоб включити останній елемент визначеної послідовності, можна використовувати метод np.linspace

In [62]:
import numpy as np

a = np.linspace(1, 5, num=5)
b = np.linspace(1, 3, num=3)
print(a)
print(b)


[1. 2. 3. 4. 5.]
[1. 2. 3.]


# Є можливість створювати масиви та матриці наповнені випадковими значеннями

In [75]:
import numpy as np

a = np.random.random(3)
b = np.random.random((3, 3))
print(a)
print(b)


[0.60446654 0.37213342 0.60949272]
[[0.60193181 0.08360347 0.58978739]
 [0.05013233 0.41953692 0.99149063]
 [0.50266427 0.78122642 0.02765872]]


Індексація

In [76]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[1:])
print(a[:2])


1
[2 3 4 5]
[1 2]


# 
Індексація багатовимірного масиву NumPy може здійснюватись як і індексація звичайного списку списків у Python: елемент з 
i
i-ого рядка та 
j
j-ого стовця можна отримати вказавши ці індекси в окремих квадратних дужках m[i][j], або ж ми можемо використати кортеж цілих чисел m[i, j]:

In [77]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1, 1])
print(a[1:, 1])
print(a[0, :2])


5
[5 8]
[1 2]


In [81]:
b = np.zeros((2, 3), dtype="u4")
print(b)


[[0 0 0]
 [0 0 0]]


In [82]:
import numpy as np

a = np.array([u"\u2211", u"\u220F"], dtype="U")
print(a)  # ['∑' '∏']


['∑' '∏']


In [ ]:
# Агрегування в NumPy

In [83]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean()) # середнє арифметичне
print(a.prod()) # перемножити всі елементи


1
5
15
3.0
120


In [84]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())


1
9
45
5.0
362880
