<a href="https://colab.research.google.com/github/MariiaSam/data_science/blob/main/%D0%9A%D0%BE%D0%BF%D1%96%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%BD%D0%B8%D0%BA%D0%B0_%22%D0%A3%D1%80%D0%BE%D0%BA_2_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


In [4]:
v1 = np.matrix([1, 2, 3, 4, 5])
print(v1)

v2 = v1.T
print(v2)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


1. Напишіть функцію, яка перевертає вектор у зворотному порядку

In [22]:
v = np.array([1, 2,3,4,5])
print(v[::-1])
v = np.flip(v)
print(v)

[5 4 3 2 1]
[5 4 3 2 1]


2.Обчислити середнє значення вектора

In [6]:
print(np.mean(v))

3.0


3.Знайти найбільший і найменший елементи вектора

In [8]:
print(np.max(v))
print(np.min(v))

5
1


4.Обчислити скалярний добуток (dot product) двох векторів

In [15]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(np.dot(v1, v2))
print((v1*v2))

32
[ 4 10 18]


5.Напишіть функцію, яка нормалізує вектор (зводить до одиничної довжини).

In [14]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)
print(norm)
print(v/norm)

7.416198487095663
[0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]


6.Перевірити, чи є вектори ортогональними

In [16]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
print(np.dot(v1, v2))

0


7. Вивести вектор без дублікатів

In [17]:
v = np.array([1, 2, 3, 4, 5, 2])
print(np.unique(v))

[1 2 3 4 5]


8.Знайти вектор, що є різницею між двома векторами

In [20]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


9.Перевірити, до дорівнює довжина вектора 5

In [24]:
vector = np.array([1,2,3, 4, 5])
length = np.linalg.norm(vector)
print(np.isclose(length, 7.416198487095663))
print(np.isclose(length, 5))


True
False


10. Задати матрицю, заповнену випадковими числами

In [25]:
a = np.random.randint(0, 10, (3, 3))
print(a)

[[7 3 7]
 [2 0 0]
 [8 4 7]]


11. Обчислити визначник матриці

In [26]:
print(np.linalg.det(a))

13.999999999999996


12. Знаходження оберненої матриці

In [27]:
print(np.linalg.inv(a))

[[ 0.          0.5         0.        ]
 [-1.         -0.5         1.        ]
 [ 0.57142857 -0.28571429 -0.42857143]]


13. Розв'яжіть систему лінійних рівнянь A⋅x=b, де A – матриця коефіцієнтів, 𝑏
 – вектор вільних членів.

In [28]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])
x = np.linalg.solve(a, b)
print(x)
inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)


[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


14. Множення двох матриць

In [30]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])
print(np.dot(a, b))


[-2 -6 16]


In [32]:
a = np.matrix([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.matrix([[5, 3, 4], [0, 2, 5], [2, 7, 4]])
print(np.dot(a, b))

[[ -3 -19   3]
 [ -6 -17  -2]
 [  0  33  22]]


In [33]:
a = np.matrix([[1, 3, -4], [0, 2, -3]])
b = np.matrix([[5, 3, 4], [0, 2, 5], [2, 7, 4]])
print(a)
print(b)
print(np.dot(a, b))

[[ 1  3 -4]
 [ 0  2 -3]]
[[5 3 4]
 [0 2 5]
 [2 7 4]]
[[ -3 -19   3]
 [ -6 -17  -2]]


15. Транспонування матриці

16. Перевірка симетричності матриці

In [ ]:
np.allclose(matrix, matrix.T)

17. Обчислення сліду матриці

In [ ]:
np.trace(matrix)

18. Сума матриць

In [ ]:
np.add(a, b)

19. Піднесення матриці до ступеня

In [ ]:
np.linalg.matrix_power(matrix, power)

20.Сортування рядків або стовпців матриці

In [ ]:
np.sort(matrix, axis=1)

In [ ]:
np.sort(matrix, axis=0)

In [ ]:
# Підрахунок суми елементів кожного рядка і зміна форми на (n, 1)
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)
#В результаті отримали вектор - стовпчик