In [1]:
import tensorflow as tf


1. Загрузите готовый набор данных.

2. Создайте модель машинного обучения нейронной сети, которая классифицирует изображения.

3. Обучите эту нейронную сеть.

4. Оцените точность модели.

# **1. Загрузите и подготовьте набор данных MNIST**
**Преобразуйте данные выборки из целых чисел в числа с плавающей запятой:**

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


# **2. Построить модель машинного обучения**
***Создайте модель tf.keras.Sequential путем наложения слоев.***

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

# layers екземпляр шару.

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


**1.models.Sequential([ ... ])
Sequential — це спосіб організувати шари нейронної мережі в лінійну (послідовну) модель, тобто шари розташовуються один за одним у порядку, в якому вони вказані. Це підходить для більш простих архітектур, де інформація проходить через кожен шар один раз, не повертаючись до попередніх шарів.**

**2. layers.Flatten(input_shape=(28, 28)) Цей шар перетворює вхідні дані з двовимірного формату 28x28 (розмірність одного зображення) на одномірний вектор із 784 елементів (28 * 28 = 784). Навіщо це потрібно? Шари нейронної мережі, такі як Dense, очікують, що вхід буде одномірним вектором. Flatten дозволяє нам передавати зображення в наступні шари мережі у форматі, який їм підходить.
input_shape=(28, 28) означає, що на вхід подаються зображення розміром 28x28 пікселів (типовий розмір зображень у наборі даних MNIST).**

**3. layers.Dense(128, activation='relu') Цей шар є повнозв'язним (Dense) шаром, що містить 128 нейронів. Що таке Dense (або fully-connected) шар? У цьому шарі кожен нейрон з'єднаний із кожним входом із попереднього шару. Ці з’єднання означають, що цей шар може "навчитися" більш складним патернам вхідних даних. 128 — кількість нейронів у цьому шарі. Більша кількість нейронів дозволяє моделі вивчати більше особливостей, але також збільшує обчислювальну складність.
activation='relu' — функція активації "Rectified Linear Unit" (ReLU). ReLU перетворює кожне значення на позитивне, якщо воно більше нуля, або на нуль, якщо менше. Це допомагає нейронній мережі вчитися нелінійним залежностям, що робить її більш потужною в обробці складних патернів.**

**4. layers.Dropout(0.2) Цей шар випадковим чином "відключає" 20% нейронів у попередньому шарі під час кожного етапу навчання (epoch). Навіщо використовується Dropout? Dropout запобігає перенавчанню моделі (overfitting), тобто моделі краще узагальнювати на нові дані. Зазвичай, коли всі нейрони постійно активні, модель може дуже "запам'ятати" тренувальні дані, що призводить до низької якості на тестових даних.0.2 означає, що в кожну ітерацію 20% нейронів будуть відключені випадковим чином.**

**5. layers.Dense(10, activation='softmax') Останній шар також є повнозв'язним, але тепер із 10 нейронами. Чому 10 нейронів? У нас 10 класів (цифри від 0 до 9) для класифікації, тому кожен нейрон представляє ймовірність для одного з класів.
activation='softmax' — функція активації softmax. Вона перетворює вихідні значення на ймовірності, які в сумі дорівнюють 1, що зручно для задачі класифікації. Кожен нейрон видає значення, що представляє ймовірність належності до одного з 10 класів.**

У нейронній мережі прихований шар — це будь-який шар, розташований між вхідним та вихідним шарами. У моїй моделі шар Dense(128, activation='relu') розташований після вхідного шару (де йде розгортка Flatten) і перед вихідним шаром Dense(10, activation='softmax'). Тому цей шар є прихованим.

Що робить прихований шар
Приховані шари виконують обчислення, які дозволяють моделі виявляти патерни та особливості даних. У цьому шарі:

128 нейронів надають модель більше можливостей для виявлення складних патернів у вхідних даних.
Функція активації relu (Rectified Linear Unit) дозволяє моделі навчатися нелінійних взаємозв'язків між ознаками в даних.
Приховані шари зазвичай застосовуються для навчання складніших патернів, які потім використовуються вихідним шаром для формування остаточного прогнозу чи класифікації.

***Для каждого примера модель возвращает вектор оценок логитов или логарифмических шансов , по одному для каждого класса.***

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.49228305, -0.44323528,  0.0836733 ,  0.31902844,  0.09246992,
        -0.17969567,  0.20281628,  0.5474887 ,  0.13305305, -0.10947332]],
      dtype=float32)

**Функция tf.nn.softmax преобразует эти логиты в вероятности для каждого класса:**


In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.05744083, 0.06032841, 0.10217752, 0.12929116, 0.1030803 ,
        0.07851917, 0.11510614, 0.16247548, 0.10734968, 0.08423118]],
      dtype=float32)

***Определите функцию потерь для обучения с использованием losses.SparseCategoricalCrossentropy , которая принимает вектор логитов и индекс True и возвращает скалярную потерю для каждого примера.***

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn

Эта потеря равна отрицательной логарифмической вероятности истинного класса: потеря равна нулю, если модель уверена в правильном классе.

Эта необученная модель дает вероятности, близкие к случайным (1/10 для каждого класса), поэтому начальная потеря должна быть близка к -tf.math.log(1/10) ~= 2.3 .

In [8]:
loss_fn(y_train[:1], predictions).numpy()


2.5444126

***Перед началом обучения настройте и скомпилируйте модель с помощью Model.compile . Установите класс optimizer на adam , установите loss на функцию loss_fn , которую вы определили ранее, и укажите метрику, которая будет оцениваться для модели, установив параметр metrics на accuracy .***

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# ***3. Обучите и оцените свою модель***

In [10]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8600 - loss: 0.4814
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9542 - loss: 0.1563
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9668 - loss: 0.1126
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9727 - loss: 0.0870
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9776 - loss: 0.0712


***Метод Model.evaluate проверяет производительность моделей, обычно на " Validation-set " или " Test-set "***

In [11]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 1s - 2ms/step - accuracy: 0.9752 - loss: 0.0818


[0.08183000981807709, 0.9751999974250793]

***Если вы хотите, чтобы ваша модель возвращала вероятность, вы можете обернуть обученную модель и прикрепить к ней softmax:***

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [13]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.24015736e-07, 9.61562563e-09, 9.29221017e-07, 1.30649481e-04,
        2.20125654e-12, 5.22898517e-06, 2.58797341e-11, 9.99853730e-01,
        2.60843694e-06, 6.61347394e-06],
       [7.01204854e-08, 2.20069196e-04, 9.99449193e-01, 1.95747780e-04,
        2.52512941e-12, 1.68335337e-05, 9.09873279e-07, 4.00811220e-13,
        1.17111835e-04, 2.56190347e-11],
       [5.30398950e-07, 9.98789608e-01, 6.78714205e-05, 1.11753288e-05,
        2.41067901e-04, 1.89546245e-05, 5.52218189e-05, 5.82071196e-04,
        2.32169274e-04, 1.35339212e-06],
       [9.99683976e-01, 7.59774466e-08, 7.38117451e-05, 4.26418092e-06,
        2.75180301e-09, 3.42497551e-05, 3.21789630e-05, 6.12330696e-05,
        2.83209971e-07, 1.09932414e-04],
       [4.60761930e-06, 3.62312591e-07, 5.25100550e-05, 7.61053286e-07,
        9.90703702e-01, 6.65600601e-06, 1.38740152e-05, 6.03424327e-04,
        2.90791286e-06, 8.61124881e-03]], dtype=float32)>

In [14]:
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_accuracy:.4f}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9703 - loss: 0.0944
Test accuracy: 0.9752


# ***Приклад моделі з кількома вхідними шарами***
Припустимо, ми працюємо з моделлю, де є два типи вхідних даних:

***Зображення (розмір 28x28) для обробки за допомогою згорткової мережі.
Табличні дані (кілька числових ознак), які можна обробити через звичайний повнозв'язний шар.***

In [22]:
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Dense, Flatten, Concatenate, Conv2D, MaxPooling2D

# Вхід для зображень (28x28)
image_input = Input(shape=(28, 28, 1), name='image_input')
x1 = Conv2D(32, (3, 3), activation='relu')(image_input)
x1 = MaxPooling2D((2, 2))(x1)
x1 = Flatten()(x1)

# Вхід для числових ознак
numeric_input = Input(shape=(10,), name='numeric_input')  # Наприклад, 10 числових ознак
x2 = Dense(64, activation='relu')(numeric_input)

# Об'єднання обох потоків
merged = Concatenate()([x1, x2])
output = Dense(1, activation='sigmoid')(merged)  # Припустимо, завдання - бінарна класифікація

# Створення моделі
model = Model(inputs=[image_input, numeric_input], outputs=output)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()




Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ image_input (InputLayer)  │ (None, 28, 28, 1)      │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_3 (Conv2D)         │ (None, 26, 26, 32)     │            320 │ image_input[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ max_pooling2d_3           │ (None, 13, 13, 32)     │              0 │ conv2d_3[0][0]         │
│ (MaxPooling2D)            │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ numeric_input             │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ flatten_4 (Flatten)       │ (None, 5408)           │              0 │ max_pooling2d_3[0][0]  │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_8 (Dense)           │ (None, 64)             │            704 │ numeric_input[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ concatenate_3             │ (None, 5472)           │              0 │ flatten_4[0][0],       │
│ (Concatenate)             │                        │                │ dense_8[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_9 (Dense)           │ (None, 1)              │          5,473 │ concatenate_3[0][0]    │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 6,497 (25.38 KB)

 Trainable params: 6,497 (25.38 KB)

 Non-trainable params: 0 (0.00 B)

***Input для кожного типу даних: image_input для зображень і numeric_input для числових ознак.***
***Окремі обчислювальні шляхи: обробка зображень через згорткові шари та обробка числових ознак через повнозв'язні шари.***
***Об'єднання (Concatenate) потоків даних перед передачею їх до вихідного шару.***

In [27]:
import numpy as np


x_image_data = np.random.rand(1000, 28, 28, 1)
# Числові дані (наприклад, 1000 прикладів з 10 ознаками)
x_numeric_data = np.random.rand(1000, 10)
# Мітки класів (бінарна класифікація, тому 0 або 1)
y_labels = np.random.randint(0, 2, 1000)


model.fit(
    {'image_input': x_image_data, 'numeric_input': x_numeric_data},
    y_labels,
    epochs=10,
    batch_size=32
)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.4929 - loss: 0.7031
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.5083 - loss: 0.6912
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.6189 - loss: 0.6822
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5729 - loss: 0.6696
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5482 - loss: 0.6588
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6044 - loss: 0.6508
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7540 - loss: 0.6214
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8225 - loss: 0.5975
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7583 - loss: 0.5892
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8448 - loss: 0.5503


x_image_data містить масив зображень розміром (1000, 28, 28, 1), де 1000 — кількість зразків, 28x28 — розмір зображення, а 1 — кількість кольорових каналів.

x_numeric_data — масив числових даних розміром (1000, 10).

y_labels містить мітки класів для кожного зразка.