In [21]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [22]:
tf.constant([[4]])

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[4]])>

In [23]:
tf.random.uniform(shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0.34082973, 0.32244658, 0.04638827, 0.8424312 ],
        [0.9611205 , 0.3933493 , 0.2930938 , 0.65968287],
        [0.71205807, 0.8182266 , 0.99067295, 0.71724164]],

       [[0.74020433, 0.5717248 , 0.3624767 , 0.693418  ],
        [0.57450604, 0.33083308, 0.16639555, 0.25006163],
        [0.41239238, 0.60892797, 0.6368432 , 0.5941107 ]]], dtype=float32)>

In [25]:
tf.fill([2, 3, 4], 3)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])>

In [26]:
tf.zeros([2, 3, 4])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [27]:
tf.ones([2, 3, 4])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [30]:
tensor = tf.ones([2, 3, 4])

In [31]:
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [32]:
tensor.ndim

3

In [33]:
a = tf.constant([[1, 2], 
                 [3, 4]])
b = tf.constant([[5, 6], 
                 [7, 8]])
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [34]:
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [35]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [36]:
a * b 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [37]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [38]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [39]:
tf.subtract(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]])>

In [40]:
a - b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]])>

In [41]:
def f(x):
    return 1 / x ** 2

x = tf.Variable(2.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = f(x)
    dydx = tape.gradient(y, x)
    print(dydx)

tf.Tensor(-0.25, shape=(), dtype=float32)
