In [87]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)

numpy.ndarray

Створення масиву 

In [89]:
import numpy as np
a = np.array([2, 3, 4])
a
a.dtype
print(a)
b = np.array([1.2, 3.5, 5.1])
b.dtype
print(b)

[2 3 4]
[1.2 3.5 5.1]


На відміну від багатьох матричних мов, оператор продукту *працює поелементно в масивах NumPy. Матричний добуток можна виконати за допомогою @оператора (у python >=3.5) або dotфункції або методу:

In [91]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product
A @ B     # matrix product
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])